version: '3.3'
services:
  back:
    image: golang_graphql
    build: ./
    ports:
      - "8080:8080"
    networks:
      - pcb-app
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "${MYSQL_USERNAME}"
      # You can use whatever password you like
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3309:3309'
    volumes:
      - pcb-db:/var/lib/mysql
    networks:
      - pcb-app

networks:
  pcb-app:
    driver: bridge

volumes:
  pcb-db:
    driver: local