version: '3.3'
services:
  pcBuilder_back:
    image: golang_graphql
    build: ./
    ports:
      - "8083:8083"
    networks:
      - pcb-app
    depends_on:
      - pcBuilder_db

  pcBuilder_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "${MYSQL_USERNAME}"
      # You can use whatever password you like
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - pcb-db:/var/lib/mysql

networks:
  pcb-app:
    driver: bridge
# Names our volume
volumes:
  pcb-db:
    driver: local