// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CPU struct {
	ID         int     `json:"id"`
	Name       string  `json:"name"`
	Company    *string `json:"company"`
	Cores      int     `json:"cores"`
	Clockspeed string  `json:"clockspeed"`
	Sockets    int     `json:"sockets"`
	Price      float64 `json:"price"`
}

type Case struct {
	ID       int     `json:"id"`
	Name     string  `json:"name"`
	Company  *string `json:"company"`
	Windowed *bool   `json:"windowed"`
	Material string  `json:"material"`
	Price    float64 `json:"price"`
}

type GraphicsCard struct {
	ID        int     `json:"id"`
	Name      string  `json:"name"`
	Company   *string `json:"company"`
	Gpu       string  `json:"gpu"`
	Memory    int     `json:"memory"`
	CoreClock string  `json:"core_clock"`
	Price     float64 `json:"price"`
}

type Memory struct {
	ID             int     `json:"id"`
	Name           string  `json:"name"`
	Company        *string `json:"company"`
	Frequency      string  `json:"frequency"`
	CasLatency     string  `json:"cas_latency"`
	MemoryChannels string  `json:"memory_channels"`
	Price          float64 `json:"price"`
}

type Monitor struct {
	ID         int     `json:"id"`
	Name       string  `json:"name"`
	Company    *string `json:"company"`
	Resolution string  `json:"resolution"`
	Hz         int     `json:"hz"`
	Price      float64 `json:"price"`
}

type Motherboard struct {
	ID            int     `json:"id"`
	Name          string  `json:"name"`
	Company       *string `json:"company"`
	FormFactor    string  `json:"form_factor"`
	Sockets       int     `json:"sockets"`
	Chipsets      int     `json:"chipsets"`
	PciSlots      int     `json:"pci_slots"`
	RAMSlots      int     `json:"ram_slots"`
	InternalPorts int     `json:"internal_ports"`
	ExternalPorts int     `json:"external_ports"`
	Price         float64 `json:"price"`
}

type NewCPU struct {
	Name       string  `json:"name"`
	Company    *string `json:"company"`
	Cores      int     `json:"cores"`
	Clockspeed string  `json:"clockspeed"`
	Sockets    int     `json:"sockets"`
	Price      float64 `json:"price"`
}

type NewCase struct {
	Name     string  `json:"name"`
	Company  *string `json:"company"`
	Windowed *bool   `json:"windowed"`
	Material string  `json:"material"`
	Price    float64 `json:"price"`
}

type NewGraphicCard struct {
	Name      string  `json:"name"`
	Company   *string `json:"company"`
	Gpu       string  `json:"gpu"`
	Memory    int     `json:"memory"`
	CoreClock string  `json:"core_clock"`
	Price     float64 `json:"price"`
}

type NewMemory struct {
	Name           string  `json:"name"`
	Company        *string `json:"company"`
	Frequency      string  `json:"frequency"`
	CasLatency     string  `json:"cas_latency"`
	MemoryChannels string  `json:"memory_channels"`
	Price          float64 `json:"price"`
}

type NewMonitor struct {
	Name       string  `json:"name"`
	Company    *string `json:"company"`
	Resolution string  `json:"resolution"`
	Hz         int     `json:"hz"`
	Price      float64 `json:"price"`
}

type NewMotherBoard struct {
	Name          string  `json:"name"`
	Company       *string `json:"company"`
	FormFactor    string  `json:"form_factor"`
	Sockets       int     `json:"sockets"`
	Chipsets      int     `json:"chipsets"`
	PciSlots      int     `json:"pci_slots"`
	RAMSlots      int     `json:"ram_slots"`
	InternalPorts int     `json:"internal_ports"`
	ExternalPorts int     `json:"external_ports"`
	Price         float64 `json:"price"`
}

type NewOs struct {
	Name    string  `json:"name"`
	Company *string `json:"company"`
	Price   int     `json:"price"`
}

type NewPowerSupply struct {
	Name       string  `json:"name"`
	Company    *string `json:"company"`
	FormFactor string  `json:"form_factor"`
	Modularity string  `json:"modularity"`
	Price      float64 `json:"price"`
}

type NewStorage struct {
	Name     string  `json:"name"`
	Company  *string `json:"company"`
	Format   string  `json:"format"`
	Capacity string  `json:"capacity"`
	Speed    string  `json:"speed"`
	Price    float64 `json:"price"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type OperatingSystem struct {
	ID      int     `json:"id"`
	Name    string  `json:"name"`
	Company *string `json:"company"`
	Price   int     `json:"price"`
}

type Pc struct {
	Name string `json:"name"`
	ID   int    `json:"id"`
}

type PowerSupply struct {
	ID         int     `json:"id"`
	Name       string  `json:"name"`
	Company    *string `json:"company"`
	FormFactor string  `json:"form_factor"`
	Modularity string  `json:"modularity"`
	Price      float64 `json:"price"`
}

type Storage struct {
	ID       int     `json:"id"`
	Name     string  `json:"name"`
	Company  *string `json:"company"`
	Format   string  `json:"format"`
	Capacity string  `json:"capacity"`
	Speed    string  `json:"speed"`
	Price    float64 `json:"price"`
}

type UpdatedCPU struct {
	Name       string  `json:"name"`
	ID         int     `json:"id"`
	Company    *string `json:"company"`
	Cores      int     `json:"cores"`
	Clockspeed string  `json:"clockspeed"`
	Sockets    int     `json:"sockets"`
	Price      float64 `json:"price"`
}

type UpdatedCase struct {
	Name     string  `json:"name"`
	ID       int     `json:"id"`
	Company  *string `json:"company"`
	Windowed *bool   `json:"windowed"`
	Material string  `json:"material"`
	Price    float64 `json:"price"`
}

type UpdatedGraphicCard struct {
	Name      string  `json:"name"`
	ID        int     `json:"id"`
	Company   *string `json:"company"`
	Gpu       string  `json:"gpu"`
	Memory    int     `json:"memory"`
	CoreClock string  `json:"core_clock"`
	Price     float64 `json:"price"`
}

type UpdatedMemory struct {
	Name           string  `json:"name"`
	ID             int     `json:"id"`
	Company        *string `json:"company"`
	Frequency      string  `json:"frequency"`
	CasLatency     string  `json:"cas_latency"`
	MemoryChannels string  `json:"memory_channels"`
	Price          float64 `json:"price"`
}

type UpdatedMonitor struct {
	Name       string  `json:"name"`
	ID         int     `json:"id"`
	Company    *string `json:"company"`
	Resolution string  `json:"resolution"`
	Hz         int     `json:"hz"`
	Price      float64 `json:"price"`
}

type UpdatedMotherboard struct {
	Name          string  `json:"name"`
	ID            int     `json:"id"`
	Company       *string `json:"company"`
	FormFactor    string  `json:"form_factor"`
	Sockets       int     `json:"sockets"`
	Chipsets      int     `json:"chipsets"`
	PciSlots      int     `json:"pci_slots"`
	RAMSlots      int     `json:"ram_slots"`
	InternalPorts int     `json:"internal_ports"`
	ExternalPorts int     `json:"external_ports"`
	Price         float64 `json:"price"`
}

type UpdatedOs struct {
	Name    string  `json:"name"`
	ID      int     `json:"id"`
	Company *string `json:"company"`
	Price   int     `json:"price"`
}

type UpdatedPowerSupply struct {
	Name       string  `json:"name"`
	ID         int     `json:"id"`
	Company    *string `json:"company"`
	FormFactor string  `json:"form_factor"`
	Modularity string  `json:"modularity"`
	Price      float64 `json:"price"`
}

type UpdatedStorage struct {
	Name     string  `json:"name"`
	ID       int     `json:"id"`
	Company  *string `json:"company"`
	Format   string  `json:"format"`
	Capacity string  `json:"capacity"`
	Speed    string  `json:"speed"`
	Price    float64 `json:"price"`
}

type UpdatedUser struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type User struct {
	ID             int    `json:"id"`
	Username       string `json:"username"`
	Password       string `json:"password"`
	Email          string `json:"email"`
	PcCollectionID int    `json:"pc_collection_id"`
}
